-- My code starts here
Select CUSTOMER_NAME from CUSTOMER where CUSTOMER_NAME Like 'J%';
Select CUSTOMER_CITY from CUSTOMER where CUSTOMER_CITY Like '%o%o%';

SELECT DISTINCT BRANCH_NAME FROM BRANCH;

SELECT BALANCE, BALANCE * 1.10 AS INCREMENTED FROM ACCOUNT;

SELECT * FROM CUSTOMER C, DEPOSITOR D WHERE C.CUSTOMER_NAME = D.CUSTOMER_NAME;

SELECT * FROM CUSTOMER NATURAL JOIN DEPOSITOR;

SELECT * FROM CUSTOMER C JOIN DEPOSITOR D ON C.CUSTOMER_NAME = D.CUSTOMER_NAME;

SELECT * FROM CUSTOMER JOIN DEPOSITOR USING(CUSTOMER_NAME);

SELECT * FROM CUSTOMER C JOIN DEPOSITOR D ON C.CUSTOMER_NAME = D.CUSTOMER_NAME JOIN ACCOUNT A ON D.ACCOUNT_NUMMBER = A.ACCOUNT_NUMBER;

SELECT CUSTOMER_NAME FROM DEPOSITOR UNION SELECT CUSTOMER_NAME FROM BORROWER;

SELECT CUSTOMER_NAME FROM DEPOSITOR MINUS SELECT CUSTOMER_NAME FROM BORROWER;

SELECT SUM(assets) FROM BRANCH;