SELECT ASCII('a') FROM DUAL;
SELECT CONCAT(CUSTOMER_STREET, CUSTOMER_CITY) FROM CUSTOMER;
SELECT CONCAT(CUSTOMER_STREET, CUSTOMER_CITY) AS ADDRESS FROM CUSTOMER;
SELECT CONCAT(CONCAT(CUSTOMER_STREET, ', '), CUSTOMER_CITY) AS ADDRESS FROM CUSTOMER;
SELECT CUSTOMER_STREET || ', ' || CUSTOMER_CITY AS ADDRESS FROM CUSTOMER;

SELECT INITCAP('hello world') FROM DUAL;
SELECT INSTR('hello world','o') FROM DUAL;

SELECT CUSTOMER_NAME FROM CUSTOMER WHERE LENGTH(CUSTOMER_NAME) > 5;
SELECT CUSTOMER_NAME FROM CUSTOMER WHERE CUSTOMER_NAME LIKE '_____%';

SELECT UPPER('Hi!') FROM DUAL;
SELECT LOWER('Hi!') FROM DUAL;

SELECT LPAD(CUSTOMER_NAME, 4+LENGTH(CUSTOMER_NAME), 'Mr. ') FROM CUSTOMER;
SELECT RPAD(CUSTOMER_NAME, 4+LENGTH(CUSTOMER_NAME), 'Mr. ') FROM CUSTOMER;

SELECT LTRIM('xyxzyyytech','xy') FROM DUAL;
SELECT RTRIM('xyxzyyytech','xy') FROM DUAL;