-- In Not IN
SELECT
  COURSE_ID
FROM 
  Section
Where
  SEMESTER = 'Fall' AND YEAR = 2009;

SELECT
  COURSE_ID
FROM 
    SECTION
Where
  SEMESTER = 'Fall' AND YEAR = 2009 AND
  COURSE_ID IN (SELECT COURSE_ID
                FROM SECTION
                WHERE SEMESTER = 'Spring' AND YEAR = 2010);

SELECT
  COURSE_ID
FROM 
    SECTION
Where
  SEMESTER = 'Fall' AND YEAR = 2009 AND
  COURSE_ID NOT IN (SELECT COURSE_ID
FROM SECTION
WHERE SEMESTER = 'Spring' AND YEAR = 2010);

SELECT ID, COURSE_ID, SEC_ID, SEMESTER, YEAR
FROM TAKES
WHERE (COURSE_ID, SEC_ID, SEMESTER, YEAR) IN (SELECT COURSE_ID, SEC_ID, SEMESTER, YEAR
FROM TEACHES
WHERE ID = 10101);

SELECT COUNT(DISTINCT ID)
FROM TAKES
WHERE (COURSE_ID, SEC_ID, SEMESTER, YEAR) IN (SELECT COURSE_ID, SEC_ID, SEMESTER, YEAR
FROM TEACHES
WHERE ID = 10101);

-- SOME/ALL/ANY

SELECT NAME
FROM INSTRUCTOR
WHERE SALARY > SOME(SELECT SALARY
FROM INSTRUCTOR
WHERE DEPT_NAME = 'Biology')

SELECT NAME
FROM INSTRUCTOR
WHERE SALARY > ANY(SELECT SALARY
FROM INSTRUCTOR
WHERE DEPT_NAME = 'Biology')

SELECT NAME
FROM INSTRUCTOR
WHERE SALARY > ALL(SELECT SALARY
FROM INSTRUCTOR
WHERE DEPT_NAME = 'Biology')

SELECT NAME
FROM INSTRUCTOR
WHERE SALARY < SOME(SELECT SALARY
FROM INSTRUCTOR
WHERE DEPT_NAME = 'Biology')

-- WITH clause

WITH TS AS (
    SELECT SUM(SALARY) as SALARY ,DEPT_NAME
    FROM INSTRUCTOR
    GROUP BY DEPT_NAME
), AVGS AS (
    SELECT AVG(SALARY) as AVGS
    FROM TS
) SELECT DEPT_NAME
FROM TS , AVGS
Where TS.SALARY > AVGS.AVGS;