SELECT * FROM CUSTOMER;

CREATE OR REPLACE VIEW CUSTOMER_AT_STAMFORD AS
   (SELECT *
    FROM CUSTOMER
    WHERE CUSTOMER_CITY= 'Stamford');

SELECT * FROM CUSTOMER_AT_STAMFORD;

CREATE OR REPLACE VIEW CUSTOMER_AT_WALNUT_STREET AS
 (SELECT CUSTOMER_NAME, CUSTOMER_STREET
  FROM CUSTOMER_AT_STAMFORD
  WHERE CUSTOMER_STREET = 'Walnut');

SELECT * FROM CUSTOMER_AT_WALNUT_STREET;

CREATE USER C##NITU IDENTIFIED BY CSE3027;

grant resource, connect, create session, unlimited tablespace,
create table, create view to C##NITU;

GRANT SELECT, INSERT 
ON CUSTOMER_AT_STAMFORD
TO C##NITU WITH GRANT OPTION;

 
INSERT INTO CUSTOMER_AT_STAMFORD 
VALUES('Y','GREENROAD','DHAKA');

REVOKE SELECT
ON CUSTOMER_AT_STAMFORD
FROM C##NITU;


------- WRITE IN DIFFERENT USER

SELECT * FROM SYSTEM.CUSTOMER_AT_STAMFORD;

INSERT INTO SYSTEM.CUSTOMER_AT_STAMFORD 
VALUES('X','GREENROAD','DHAKA');

SELECT * FROM USER_TAB_PRIVS;
