@ C:\Users\Student\Downloads\University.sql

SELECT * FROM classroom ;
SELECT * FROM department ;
SELECT * FROM course ;
SELECT * FROM instructor ;
SELECT * FROM section ;
SELECT * FROM teaches ;
SELECT * FROM student ;
SELECT * FROM takes ;
SELECT * FROM advisor ;
SELECT * FROM time_slot ;
SELECT * FROM prereq ;

SELECT COURSE_ID
FROM SECTION
WHERE SEMESTER = 'Fall' AND YEAR = 2009 AND 
COURSE_ID NOT IN (SELECT COURSE_ID
                FROM SECTION
                WHERE SEMESTER = 'Spring' AND YEAR = 2010);




SELECT COUNT(DISTINCT ID)
FROM TAKES
WHERE (COURSE_ID, SEC_ID, SEMESTER, YEAR) 
                IN(SELECT COURSE_ID, SEC_ID, SEMESTER, YEAR
                FROM TEACHES
                WHERE ID = 10101);


INSERT INTO INSTRUCTOR VALUES(11111,'NITU','Biology',85000);


SELECT NAME, SALARY
FROM INSTRUCTOR
WHERE SALARY <ALL(SELECT SALARY
                FROM INSTRUCTOR
                WHERE DEPT_NAME = 'Biology');

SELECT COURSE_ID
FROM SECTION S1
WHERE SEMESTER = 'Fall' AND YEAR = 2009 AND 
       NOT EXISTS (SELECT *
                FROM SECTION S2
                WHERE SEMESTER = 'Spring' AND YEAR = 2010
                AND S1.COURSE_ID= S2.COURSE_ID);              


SELECT DEPT_NAME, AVG(SALARY)AS AVG_SAL
FROM INSTRUCTOR 
GROUP BY DEPT_NAME
HAVING AVG(SALARY)>42000;

SELECT DEPT_NAME, AVG_SAL
FROM(SELECT DEPT_NAME, AVG(SALARY)AS AVG_SAL
    FROM INSTRUCTOR 
    GROUP BY DEPT_NAME)
WHERE AVG_SAL>42000;

WITH MAX_BUDGET AS
(SELECT MAX(BUDGET) AS MAX_VALUE
FROM DEPARTMENT)
SELECT DEPT_NAME, BUDGET
FROM DEPARTMENT, MAX_BUDGET
WHERE DEPARTMENT.BUDGET = MAX_BUDGET.MAX_VALUE;



WITH TOTAL_SALARY_PER_DEPT AS
(SELECT DEPT_NAME, SUM(SALARY) AS TOTAL_SAL
FROM INSTRUCTOR
GROUP BY DEPT_NAME),
TOTAL_AVG AS
(SELECT AVG(TOTAL_SAL) AS AVG
FROM TOTAL_SALARY_PER_DEPT)
SELECT DEPT_NAME
FROM TOTAL_SALARY_PER_DEPT, TOTAL_AVG
WHERE TOTAL_SAL> AVG;


INSERT INTO DEPARTMENT VALUES('English', 'AB3',888888);

SELECT * 
FROM DEPARTMENT NATURAL FULL OUTER JOIN INSTRUCTOR;


SELECT DEPT_NAME, COUNT(ID) AS NO_OF_INSTRUCTOR
FROM DEPARTMENT NATURAL LEFT OUTER JOIN INSTRUCTOR
GROUP BY DEPT_NAME;







