SELECT ASCII('A')
FROM DUAL;

SELECT CHR(97)
FROM DUAL;

SELECT * FROM customer;

SELECT CONCAT(CONCAT(CUSTOMER_STREET, ', '), CUSTOMER_CITY) AS ADDRESS
FROM CUSTOMER;

SELECT CUSTOMER_NAME, CUSTOMER_STREET || ', ' || CUSTOMER_CITY 
AS FULL_ADDRESS FROM CUSTOMER;

SELECT INITCAP('HeLlO WOrLd') 
FROM DUAL;

SELECT INSTR('Tech on the net','e', 7,1) 
FROM DUAL;

SELECT *
FROM CUSTOMER
WHERE LENGTH(CUSTOMER_NAME)>5;

SELECT *
FROM CUSTOMER
WHERE LOWER(CUSTOMER_NAME)='williams';

SELECT LPAD('tech', 8, 'ABC') FROM DUAL;

SELECT rPAD(CUSTOMER_NAME, LENGTH(CUSTOMER_NAME)+3, 'Mr.') AS NAME
FROM CUSTOMER;

SELECT rTRIM('xyxzyyyTecxyzzz','xyz') FROM DUAL;

SELECT SUBSTR('TechOn TheNet', 3,6) FROM DUAL;



SELECT ADD_MONTHS(TO_DATE('21-08-03','YY-MM-DD'),3) FROM DUAL;

SELECT SYSDATE FROM DUAL;


SELECT EXTRACT(DAY FROM DATE '2003-08-22')
from dual;

SELECT TO_CHAR(SYSDATE,'YYYY:MM:DD') FROM DUAL;

SELECT TO_DATE('2015/05/15 8:30:25', 'YYYY/MM/DD HH:MI:SS') FROM dual;


